Use variable for mini-repo
collegiumv/cv_config pull request #41
Opened 2017-09-13 19:10 UTC by m-wynn

I'd test this in check mode, but my secrets are out of date, and we don't have tags

2017-09-13 21:05 UTC, kulinacs requested changes
Like the change overall, just some minor fixes

2017-09-13 21:05 UTC, kulinacs commented on group_vars/utility.yml
> +mini-builder-packages:
Ansible doesn't understand variables with dashes in them

2017-09-13 21:05 UTC, kulinacs commented on roles/xbps-mini-repo/tasks/main.yml
> +    src: packages.list
Could we make this packages.list.j2?

2017-09-14 01:20 UTC, m-wynn commented
fixed, probably

2017-09-14 04:19 UTC, merged