Add keyboard layouts for homework
collegiumv/cv_config pull request #51
Opened 2017-11-06 06:21 UTC by m-wynn

Willy needs this for homework.

I'll push to whatever workstation he's using until it's merged

2017-11-06 17:07 UTC, kulinacs requested changes

2017-11-06 17:07 UTC, kulinacs commented on roles/workstation/tasks/main.yml
> +
Extra newline.

2017-11-06 18:15 UTC, m-wynn commented on roles/workstation/tasks/main.yml
> +
fixup'd

2017-11-15 03:04 UTC, kulinacs approved these changes

2017-11-15 03:04 UTC, kulinacs commented
Running test deployment on Oberon now. Will merge if successful.

2017-11-15 17:50 UTC, kulinacs commented
`ibus-mozc` is not a package.

2017-11-15 19:09 UTC, m-wynn commented
Yes it is?  Are we still syncing properly?

2017-11-15 19:13 UTC, dinoocch commented
https://github.com/voidlinux/void-packages/blob/master/srcpkgs/mozc/template

2019-08-20 23:04 UTC, m-wynn commented
Closing this, to clean out my GitHub notifications.  Hi guys.

2019-08-20 23:04 UTC, closed without merging